### ISSUE TITLE
Imposible hacerlo arrancar

### ISSUE THREAD

**Issue by mr0bles** [newsages/newnav#1]
Buenas, estoy intentando implementar tu sistema en una aplicación propia, pero me esta siendo imposible. 
También he probado a descargar el proyecto completo e intentar arrancarlo (con su correspondiente migrate, seed y update) y lo único que saco en claro es que tienes las vistas y los modelos, pero no encuentro el lugar donde procedes a hacer las peticiones con el servidor de SII.

Si puedes ayudarme o guiarme para poder realizar una conexión satisfactoria con el nuevo sistema de SII te lo agradecería y podría ayudarte a acabar el proyecto.

**Comment by newsages** [comment]
Este proyecto es una herramienta externa para el erp de navision versiones cliente nativo, para poder enviar soap + autenticacion con certificados,
navision genera XML desde xmlport y los envia a esta api externa, indicando, que empresa y que tipo de comunicacion/metodo soap, este servicio envia los datos a los puertos soap segun configuracion y obtiene un resultado que le es devuelto a navision y lo trata internamente por xml port: 
Ejemplo de Metodos (modelo):
1 	SuministroFactEmitidas 	A0 	SIIFacturasEmitidasAlta 	SuministroLRFacturasEmitidas 	
2 	SuministroFactEmitidas 	A1 	SIIFacturasEmitidasMod 	SuministroLRFacturasEmitidas 	
3 	SuministroFactEmitidas 		SIIFacturasEmitidasBaja 	BajaLRFacturasEmitidas 	
4 	SuministroFactEmitidas 		SIIFacturasEmitidasConsulta 	ConsultaLRFacturasEmitidas 	
5 	SuministroFactRecibidas 	A0 	SIIFacturasRecibidasAlta 	SuministroLRFacturasRecibidas 	
6 	SuministroFactRecibidas 	A1 	SIIFacturasRecibidasMod 	SuministroLRFacturasRecibidas 	
7 	SuministroFactRecibidas 		SIIFacturasRecibidasBaja 	BajaLRFacturasRecibidas 	
8 	SuministroFactRecibidas 		SIIFacturasRecibidasConsulta 	ConsultaLRFacturasRecibidas 	
9 	SuministroLRBienesInversion 	A0 	SIIBienesInversionAlta 	SuministroLRBienesInversion 	
10 	SuministroLRBienesInversion 	A1 	SIIBienesInversionMod 	SuministroLRBienesInversion 	
11 	SuministroLRBienesInversion 		SIIBienesInversionBaja 	BajaLRBienesInversion 	
12 	SuministroLRBienesInversion 		SIIBienesInversionConsulta 	ConsultaLRBienesInversion 	
13 	SuministroLRDetOperacionIntracomunitaria 	A0 	SIIDetOperacionIntraAlta 	SuministroLRDetOperacionIntracomunitaria 	
14 	SuministroLRDetOperacionIntracomunitaria 	A1 	SIIDetOperacionIntraMod 	SuministroLRDetOperacionIntracomunitaria 	
15 	SuministroLRDetOperacionIntracomunitaria 		SIIDetOperacionIntraBaja 	BajaLRDetOperacionIntracomunitaria 	
16 	SuministroLRDetOperacionIntracomunitaria 		SIIDetOperacionIntraConsulta 	ConsultaLRDetOperIntracomunitarias 

Ejemplo de Tipos Soap (Modelo):
1 	SuministroFactEmitidas 	Suministro Inmediato de Información 	https://www7.aeat.es/wlpl/SSII-FACT/ws/fe/SiiFactFEV1SOAP 	
2 	SuministroFactRecibidas 	Suministro Inmediato de Información 	https://www7.aeat.es/wlpl/SSII-FACT/ws/fr/SiiFactFRV1SOAP
3 	SuministroLRBienesInversion 	Suministro Inmediato de Información 	https://www7.aeat.es/wlpl/SSII-FACT/ws/bi/SiiFactBIV1SOAP 
4 	SuministroLRDetOperacionIntracomunitaria 	Suministro Inmediato de Información 	https://www7.aeat.es/wlpl/SSII-FACT/ws/oi/SiiFactOIV1SOAP

Como te comento, es una herramienta externa junto a codeunits en navision para lograr la comunicacion soap con certificados.

Las Comunicaciones son una implementacion de curl.
Si has trabajado con laravel, podras poner en marcha el sistema sin problemas.
Un saludo.
